"""Add raw_avatar to model User

Revision ID: 091bc8c34423
Revises: fd8d9cac54c5
Create Date: 2020-03-27 11:13:49.307543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091bc8c34423'
down_revision = 'fd8d9cac54c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('raw_avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'raw_avatar')
    # ### end Alembic commands ###
