"""Add user avatar

Revision ID: fd8d9cac54c5
Revises: 2ece612c6069
Create Date: 2020-03-26 14:46:50.031213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8d9cac54c5'
down_revision = '2ece612c6069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_l', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('avatar_m', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('avatar_s', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_s')
    op.drop_column('users', 'avatar_m')
    op.drop_column('users', 'avatar_l')
    # ### end Alembic commands ###
